FROM golang:alpine AS builder
WORKDIR /app
COPY . /app
RUN cd /app && go build -o goapp
ENTRYPOINT ["/app/goapp"]

FROM alpine:latest
COPY --from=builder /app/goapp /app/goapp
ENTRYPOINT ["/app/goapp"]
